import { Card } from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useState } from "react";
import {
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from "@/components/ui/pagination";
import { TopIngredientsPriceChart } from "./TopIngredientsPriceChart";
import { InventoryTable } from "./InventoryTable";
import { type InventoryItem, type Channel } from "@/types/inventory";

const mockInventoryData: InventoryItem[] = [
  {
    id: 1,
    name: "닭고기 (한마리)",
    category: "축산물",
    channel: "쿠팡",
    currentPrice: 8500,
    yesterdayPrice: 8700,
    weekAgoPrice: 8300,
    twoWeeksAgoPrice: 8400,
    monthAgoPrice: 8200,
    yearAgoPrice: 7800,
    trend: "down",
    isLowestPrice: true,
  },
  {
    id: 31,
    name: "닭고기 (한마리)",
    category: "축산물",
    channel: "마켓대리",
    currentPrice: 8600,
    yesterdayPrice: 8800,
    weekAgoPrice: 8400,
    twoWeeksAgoPrice: 8500,
    monthAgoPrice: 8300,
    yearAgoPrice: 7900,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 32,
    name: "닭고기 (한마리)",
    category: "축산물",
    channel: "쿠거",
    currentPrice: 8700,
    yesterdayPrice: 8900,
    weekAgoPrice: 8500,
    twoWeeksAgoPrice: 8600,
    monthAgoPrice: 8400,
    yearAgoPrice: 8000,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 2,
    name: "돼지고기 (삼겹살 1kg)",
    category: "축산물",
    channel: "쿠팡",
    currentPrice: 15000,
    yesterdayPrice: 14800,
    weekAgoPrice: 14500,
    twoWeeksAgoPrice: 14700,
    monthAgoPrice: 14200,
    yearAgoPrice: 13500,
    trend: "up",
    isLowestPrice: false,
  },
  {
    id: 33,
    name: "돼지고기 (삼겹살 1kg)",
    category: "축산물",
    channel: "마켓대리",
    currentPrice: 15200,
    yesterdayPrice: 15400,
    weekAgoPrice: 15000,
    twoWeeksAgoPrice: 15100,
    monthAgoPrice: 14900,
    yearAgoPrice: 14600,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 34,
    name: "돼지고기 (삼겹살 1kg)",
    category: "축산물",
    channel: "쿠거",
    currentPrice: 15300,
    yesterdayPrice: 15500,
    weekAgoPrice: 15100,
    twoWeeksAgoPrice: 15200,
    monthAgoPrice: 15000,
    yearAgoPrice: 14700,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 3,
    name: "소고기 (등심 1kg)",
    category: "축산물",
    channel: "쿠팡",
    currentPrice: 45000,
    yesterdayPrice: 44800,
    weekAgoPrice: 44500,
    twoWeeksAgoPrice: 44700,
    monthAgoPrice: 43200,
    yearAgoPrice: 42500,
    trend: "up",
    isLowestPrice: false,
  },
  {
    id: 35,
    name: "소고기 (등심 1kg)",
    category: "축산물",
    channel: "마켓대리",
    currentPrice: 45200,
    yesterdayPrice: 45400,
    weekAgoPrice: 45000,
    twoWeeksAgoPrice: 45100,
    monthAgoPrice: 44800,
    yearAgoPrice: 44500,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 36,
    name: "소고기 (등심 1kg)",
    category: "축산물",
    channel: "쿠거",
    currentPrice: 45300,
    yesterdayPrice: 45500,
    weekAgoPrice: 45100,
    twoWeeksAgoPrice: 45200,
    monthAgoPrice: 44900,
    yearAgoPrice: 44600,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 4,
    name: "고등어 (1마리)",
    category: "수산물",
    channel: "쿠팡",
    currentPrice: 4500,
    yesterdayPrice: 4700,
    weekAgoPrice: 4300,
    twoWeeksAgoPrice: 4400,
    monthAgoPrice: 4200,
    yearAgoPrice: 3800,
    trend: "down",
    isLowestPrice: true,
  },
  {
    id: 37,
    name: "고등어 (1마리)",
    category: "수산물",
    channel: "마켓대리",
    currentPrice: 4600,
    yesterdayPrice: 4800,
    weekAgoPrice: 4400,
    twoWeeksAgoPrice: 4500,
    monthAgoPrice: 4300,
    yearAgoPrice: 3900,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 38,
    name: "고등어 (1마리)",
    category: "수산물",
    channel: "쿠거",
    currentPrice: 4700,
    yesterdayPrice: 4900,
    weekAgoPrice: 4500,
    twoWeeksAgoPrice: 4600,
    monthAgoPrice: 4400,
    yearAgoPrice: 4000,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 5,
    name: "연어 (200g)",
    category: "수산물",
    channel: "쿠팡",
    currentPrice: 12000,
    yesterdayPrice: 12200,
    weekAgoPrice: 11800,
    twoWeeksAgoPrice: 11900,
    monthAgoPrice: 11500,
    yearAgoPrice: 11000,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 39,
    name: "연어 (200g)",
    category: "수산물",
    channel: "마켓대리",
    currentPrice: 12200,
    yesterdayPrice: 12400,
    weekAgoPrice: 12000,
    twoWeeksAgoPrice: 12100,
    monthAgoPrice: 11700,
    yearAgoPrice: 11200,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 40,
    name: "연어 (200g)",
    category: "수산물",
    channel: "쿠거",
    currentPrice: 12300,
    yesterdayPrice: 12500,
    weekAgoPrice: 12100,
    twoWeeksAgoPrice: 12200,
    monthAgoPrice: 11800,
    yearAgoPrice: 11300,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 6,
    name: "오징어 (1마리)",
    category: "수산물",
    channel: "쿠팡",
    currentPrice: 3500,
    yesterdayPrice: 3600,
    weekAgoPrice: 3400,
    twoWeeksAgoPrice: 3500,
    monthAgoPrice: 3300,
    yearAgoPrice: 3000,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 41,
    name: "오징어 (1마리)",
    category: "수산물",
    channel: "마켓대리",
    currentPrice: 3600,
    yesterdayPrice: 3700,
    weekAgoPrice: 3500,
    twoWeeksAgoPrice: 3600,
    monthAgoPrice: 3400,
    yearAgoPrice: 3100,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 42,
    name: "오징어 (1마리)",
    category: "수산물",
    channel: "쿠거",
    currentPrice: 3700,
    yesterdayPrice: 3800,
    weekAgoPrice: 3600,
    twoWeeksAgoPrice: 3700,
    monthAgoPrice: 3500,
    yearAgoPrice: 3200,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 7,
    name: "양파 (1kg)",
    category: "채소/과일",
    channel: "쿠팡",
    currentPrice: 2500,
    yesterdayPrice: 2600,
    weekAgoPrice: 2400,
    twoWeeksAgoPrice: 2500,
    monthAgoPrice: 2300,
    yearAgoPrice: 2000,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 43,
    name: "양파 (1kg)",
    category: "채소/과일",
    channel: "마켓대리",
    currentPrice: 2600,
    yesterdayPrice: 2700,
    weekAgoPrice: 2500,
    twoWeeksAgoPrice: 2600,
    monthAgoPrice: 2400,
    yearAgoPrice: 2100,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 44,
    name: "양파 (1kg)",
    category: "채소/과일",
    channel: "쿠거",
    currentPrice: 2700,
    yesterdayPrice: 2800,
    weekAgoPrice: 2600,
    twoWeeksAgoPrice: 2700,
    monthAgoPrice: 2500,
    yearAgoPrice: 2200,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 8,
    name: "감자 (1kg)",
    category: "채소/과일",
    channel: "쿠팡",
    currentPrice: 3000,
    yesterdayPrice: 3100,
    weekAgoPrice: 2900,
    twoWeeksAgoPrice: 3000,
    monthAgoPrice: 2800,
    yearAgoPrice: 2500,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 45,
    name: "감자 (1kg)",
    category: "채소/과일",
    channel: "마켓대리",
    currentPrice: 3100,
    yesterdayPrice: 3200,
    weekAgoPrice: 3000,
    twoWeeksAgoPrice: 3100,
    monthAgoPrice: 2900,
    yearAgoPrice: 2600,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 46,
    name: "감자 (1kg)",
    category: "채소/과일",
    channel: "쿠거",
    currentPrice: 3200,
    yesterdayPrice: 3300,
    weekAgoPrice: 3100,
    twoWeeksAgoPrice: 3200,
    monthAgoPrice: 3000,
    yearAgoPrice: 2700,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 9,
    name: "당근 (1kg)",
    category: "채소/과일",
    channel: "쿠팡",
    currentPrice: 2800,
    yesterdayPrice: 2900,
    weekAgoPrice: 2700,
    twoWeeksAgoPrice: 2800,
    monthAgoPrice: 2600,
    yearAgoPrice: 2300,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 47,
    name: "당근 (1kg)",
    category: "채소/과일",
    channel: "마켓대리",
    currentPrice: 2900,
    yesterdayPrice: 3000,
    weekAgoPrice: 2800,
    twoWeeksAgoPrice: 2900,
    monthAgoPrice: 2700,
    yearAgoPrice: 2400,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 48,
    name: "당근 (1kg)",
    category: "채소/과일",
    channel: "쿠거",
    currentPrice: 3000,
    yesterdayPrice: 3100,
    weekAgoPrice: 2900,
    twoWeeksAgoPrice: 3000,
    monthAgoPrice: 2800,
    yearAgoPrice: 2500,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 10,
    name: "사과 (1kg)",
    category: "채소/과일",
    channel: "쿠팡",
    currentPrice: 8000,
    yesterdayPrice: 8200,
    weekAgoPrice: 7800,
    twoWeeksAgoPrice: 7900,
    monthAgoPrice: 7700,
    yearAgoPrice: 7400,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 49,
    name: "사과 (1kg)",
    category: "채소/과일",
    channel: "마켓대리",
    currentPrice: 8200,
    yesterdayPrice: 8400,
    weekAgoPrice: 8000,
    twoWeeksAgoPrice: 8100,
    monthAgoPrice: 7900,
    yearAgoPrice: 7600,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 50,
    name: "사과 (1kg)",
    category: "채소/과일",
    channel: "쿠거",
    currentPrice: 8300,
    yesterdayPrice: 8500,
    weekAgoPrice: 8100,
    twoWeeksAgoPrice: 8200,
    monthAgoPrice: 8000,
    yearAgoPrice: 7700,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 11,
    name: "라면 (5개입)",
    category: "가공",
    channel: "쿠팡",
    currentPrice: 4500,
    yesterdayPrice: 4600,
    weekAgoPrice: 4400,
    twoWeeksAgoPrice: 4500,
    monthAgoPrice: 4300,
    yearAgoPrice: 4000,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 51,
    name: "라면 (5개입)",
    category: "가공",
    channel: "마켓대리",
    currentPrice: 4600,
    yesterdayPrice: 4700,
    weekAgoPrice: 4500,
    twoWeeksAgoPrice: 4600,
    monthAgoPrice: 4400,
    yearAgoPrice: 4100,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 52,
    name: "라면 (5개입)",
    category: "가공",
    channel: "쿠거",
    currentPrice: 4700,
    yesterdayPrice: 4800,
    weekAgoPrice: 4600,
    twoWeeksAgoPrice: 4700,
    monthAgoPrice: 4500,
    yearAgoPrice: 4200,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 12,
    name: "김치 (1kg)",
    category: "가공",
    channel: "쿠팡",
    currentPrice: 15000,
    yesterdayPrice: 15200,
    weekAgoPrice: 14800,
    twoWeeksAgoPrice: 14900,
    monthAgoPrice: 14700,
    yearAgoPrice: 14400,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 53,
    name: "김치 (1kg)",
    category: "가공",
    channel: "마켓대리",
    currentPrice: 15200,
    yesterdayPrice: 15400,
    weekAgoPrice: 15000,
    twoWeeksAgoPrice: 15100,
    monthAgoPrice: 14900,
    yearAgoPrice: 14600,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 54,
    name: "김치 (1kg)",
    category: "가공",
    channel: "쿠거",
    currentPrice: 15300,
    yesterdayPrice: 15500,
    weekAgoPrice: 15100,
    twoWeeksAgoPrice: 15200,
    monthAgoPrice: 15000,
    yearAgoPrice: 14700,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 13,
    name: "돼지갈비 (1kg)",
    category: "축산물",
    channel: "쿠팡",
    currentPrice: 18000,
    yesterdayPrice: 18200,
    weekAgoPrice: 17800,
    twoWeeksAgoPrice: 17900,
    monthAgoPrice: 17700,
    yearAgoPrice: 17400,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 55,
    name: "돼지갈비 (1kg)",
    category: "축산물",
    channel: "마켓대리",
    currentPrice: 18200,
    yesterdayPrice: 18400,
    weekAgoPrice: 18000,
    twoWeeksAgoPrice: 18100,
    monthAgoPrice: 17900,
    yearAgoPrice: 17600,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 56,
    name: "돼지갈비 (1kg)",
    category: "축산물",
    channel: "쿠거",
    currentPrice: 18300,
    yesterdayPrice: 18500,
    weekAgoPrice: 18100,
    twoWeeksAgoPrice: 18200,
    monthAgoPrice: 18000,
    yearAgoPrice: 17700,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 14,
    name: "소갈비 (1kg)",
    category: "축산물",
    channel: "쿠팡",
    currentPrice: 55000,
    yesterdayPrice: 55200,
    weekAgoPrice: 54800,
    twoWeeksAgoPrice: 54900,
    monthAgoPrice: 54700,
    yearAgoPrice: 54400,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 57,
    name: "소갈비 (1kg)",
    category: "축산물",
    channel: "마켓대리",
    currentPrice: 55200,
    yesterdayPrice: 55400,
    weekAgoPrice: 55000,
    twoWeeksAgoPrice: 55100,
    monthAgoPrice: 54900,
    yearAgoPrice: 54600,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 58,
    name: "소갈비 (1kg)",
    category: "축산물",
    channel: "쿠거",
    currentPrice: 55300,
    yesterdayPrice: 55500,
    weekAgoPrice: 55100,
    twoWeeksAgoPrice: 55200,
    monthAgoPrice: 55000,
    yearAgoPrice: 54700,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 15,
    name: "참치 (200g)",
    category: "수산물",
    channel: "쿠팡",
    currentPrice: 25000,
    yesterdayPrice: 25200,
    weekAgoPrice: 24800,
    twoWeeksAgoPrice: 24900,
    monthAgoPrice: 24700,
    yearAgoPrice: 24400,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 59,
    name: "참치 (200g)",
    category: "수산물",
    channel: "마켓대리",
    currentPrice: 25200,
    yesterdayPrice: 25400,
    weekAgoPrice: 25000,
    twoWeeksAgoPrice: 25100,
    monthAgoPrice: 24900,
    yearAgoPrice: 24600,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 60,
    name: "참치 (200g)",
    category: "수산물",
    channel: "쿠거",
    currentPrice: 25300,
    yesterdayPrice: 25500,
    weekAgoPrice: 25100,
    twoWeeksAgoPrice: 25200,
    monthAgoPrice: 25000,
    yearAgoPrice: 24700,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 16,
    name: "새우 (500g)",
    category: "수산물",
    channel: "쿠팡",
    currentPrice: 15000,
    yesterdayPrice: 15200,
    weekAgoPrice: 14800,
    twoWeeksAgoPrice: 14900,
    monthAgoPrice: 14700,
    yearAgoPrice: 14400,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 61,
    name: "새우 (500g)",
    category: "수산물",
    channel: "마켓대리",
    currentPrice: 15200,
    yesterdayPrice: 15400,
    weekAgoPrice: 15000,
    twoWeeksAgoPrice: 15100,
    monthAgoPrice: 14900,
    yearAgoPrice: 14600,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 62,
    name: "새우 (500g)",
    category: "수산물",
    channel: "쿠거",
    currentPrice: 15300,
    yesterdayPrice: 15500,
    weekAgoPrice: 15100,
    twoWeeksAgoPrice: 15200,
    monthAgoPrice: 15000,
    yearAgoPrice: 14700,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 17,
    name: "배추 (1포기)",
    category: "채소/과일",
    channel: "쿠팡",
    currentPrice: 4500,
    yesterdayPrice: 4600,
    weekAgoPrice: 4400,
    twoWeeksAgoPrice: 4500,
    monthAgoPrice: 4300,
    yearAgoPrice: 4000,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 63,
    name: "배추 (1포기)",
    category: "채소/과일",
    channel: "마켓대리",
    currentPrice: 4600,
    yesterdayPrice: 4700,
    weekAgoPrice: 4500,
    twoWeeksAgoPrice: 4600,
    monthAgoPrice: 4400,
    yearAgoPrice: 4100,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 64,
    name: "배추 (1포기)",
    category: "채소/과일",
    channel: "쿠거",
    currentPrice: 4700,
    yesterdayPrice: 4800,
    weekAgoPrice: 4600,
    twoWeeksAgoPrice: 4700,
    monthAgoPrice: 4500,
    yearAgoPrice: 4200,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 18,
    name: "무 (1개)",
    category: "채소/과일",
    channel: "쿠팡",
    currentPrice: 2500,
    yesterdayPrice: 2600,
    weekAgoPrice: 2400,
    twoWeeksAgoPrice: 2500,
    monthAgoPrice: 2300,
    yearAgoPrice: 2000,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 65,
    name: "무 (1개)",
    category: "채소/과일",
    channel: "마켓대리",
    currentPrice: 2600,
    yesterdayPrice: 2700,
    weekAgoPrice: 2500,
    twoWeeksAgoPrice: 2600,
    monthAgoPrice: 2400,
    yearAgoPrice: 2100,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 66,
    name: "무 (1개)",
    category: "채소/과일",
    channel: "쿠거",
    currentPrice: 2700,
    yesterdayPrice: 2800,
    weekAgoPrice: 2600,
    twoWeeksAgoPrice: 2700,
    monthAgoPrice: 2500,
    yearAgoPrice: 2200,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 19,
    name: "고추장 (1kg)",
    category: "가공",
    channel: "쿠팡",
    currentPrice: 8500,
    yesterdayPrice: 8600,
    weekAgoPrice: 8400,
    twoWeeksAgoPrice: 8500,
    monthAgoPrice: 8300,
    yearAgoPrice: 8000,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 67,
    name: "고추장 (1kg)",
    category: "가공",
    channel: "마켓대리",
    currentPrice: 8600,
    yesterdayPrice: 8700,
    weekAgoPrice: 8500,
    twoWeeksAgoPrice: 8600,
    monthAgoPrice: 8400,
    yearAgoPrice: 8100,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 68,
    name: "고추장 (1kg)",
    category: "가공",
    channel: "쿠거",
    currentPrice: 8700,
    yesterdayPrice: 8800,
    weekAgoPrice: 8600,
    twoWeeksAgoPrice: 8700,
    monthAgoPrice: 8500,
    yearAgoPrice: 8200,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 20,
    name: "된장 (1kg)",
    category: "가공",
    channel: "쿠팡",
    currentPrice: 7500,
    yesterdayPrice: 7600,
    weekAgoPrice: 7400,
    twoWeeksAgoPrice: 7500,
    monthAgoPrice: 7300,
    yearAgoPrice: 7000,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 69,
    name: "된장 (1kg)",
    category: "가공",
    channel: "마켓대리",
    currentPrice: 7600,
    yesterdayPrice: 7700,
    weekAgoPrice: 7500,
    twoWeeksAgoPrice: 7600,
    monthAgoPrice: 7400,
    yearAgoPrice: 7100,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 70,
    name: "된장 (1kg)",
    category: "가공",
    channel: "쿠거",
    currentPrice: 7700,
    yesterdayPrice: 7800,
    weekAgoPrice: 7600,
    twoWeeksAgoPrice: 7700,
    monthAgoPrice: 7500,
    yearAgoPrice: 7200,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 21,
    name: "닭다리 (1kg)",
    category: "축산물",
    channel: "쿠팡",
    currentPrice: 9500,
    yesterdayPrice: 9600,
    weekAgoPrice: 9400,
    twoWeeksAgoPrice: 9500,
    monthAgoPrice: 9300,
    yearAgoPrice: 9000,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 71,
    name: "닭다리 (1kg)",
    category: "축산물",
    channel: "마켓대리",
    currentPrice: 9600,
    yesterdayPrice: 9700,
    weekAgoPrice: 9500,
    twoWeeksAgoPrice: 9600,
    monthAgoPrice: 9400,
    yearAgoPrice: 9100,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 72,
    name: "닭다리 (1kg)",
    category: "축산물",
    channel: "쿠거",
    currentPrice: 9700,
    yesterdayPrice: 9800,
    weekAgoPrice: 9600,
    twoWeeksAgoPrice: 9700,
    monthAgoPrice: 9500,
    yearAgoPrice: 9200,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 22,
    name: "돼지목살 (1kg)",
    category: "축산물",
    channel: "쿠팡",
    currentPrice: 16000,
    yesterdayPrice: 16200,
    weekAgoPrice: 15800,
    twoWeeksAgoPrice: 15900,
    monthAgoPrice: 15700,
    yearAgoPrice: 15400,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 73,
    name: "돼지목살 (1kg)",
    category: "축산물",
    channel: "마켓대리",
    currentPrice: 16200,
    yesterdayPrice: 16400,
    weekAgoPrice: 16000,
    twoWeeksAgoPrice: 16100,
    monthAgoPrice: 15900,
    yearAgoPrice: 15600,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 74,
    name: "돼지목살 (1kg)",
    category: "축산물",
    channel: "쿠거",
    currentPrice: 16300,
    yesterdayPrice: 16500,
    weekAgoPrice: 16100,
    twoWeeksAgoPrice: 16200,
    monthAgoPrice: 16000,
    yearAgoPrice: 15700,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 23,
    name: "꽁치 (1마리)",
    category: "수산물",
    channel: "쿠팡",
    currentPrice: 3500,
    yesterdayPrice: 3600,
    weekAgoPrice: 3400,
    twoWeeksAgoPrice: 3500,
    monthAgoPrice: 3300,
    yearAgoPrice: 3000,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 75,
    name: "꽁치 (1마리)",
    category: "수산물",
    channel: "마켓대리",
    currentPrice: 3600,
    yesterdayPrice: 3700,
    weekAgoPrice: 3500,
    twoWeeksAgoPrice: 3600,
    monthAgoPrice: 3400,
    yearAgoPrice: 3100,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 76,
    name: "꽁치 (1마리)",
    category: "수산물",
    channel: "쿠거",
    currentPrice: 3700,
    yesterdayPrice: 3800,
    weekAgoPrice: 3600,
    twoWeeksAgoPrice: 3700,
    monthAgoPrice: 3500,
    yearAgoPrice: 3200,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 24,
    name: "갈치 (1마리)",
    category: "수산물",
    channel: "쿠팡",
    currentPrice: 12000,
    yesterdayPrice: 12200,
    weekAgoPrice: 11800,
    twoWeeksAgoPrice: 11900,
    monthAgoPrice: 11700,
    yearAgoPrice: 11400,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 77,
    name: "갈치 (1마리)",
    category: "수산물",
    channel: "마켓대리",
    currentPrice: 12200,
    yesterdayPrice: 12400,
    weekAgoPrice: 12000,
    twoWeeksAgoPrice: 12100,
    monthAgoPrice: 11900,
    yearAgoPrice: 11600,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 78,
    name: "갈치 (1마리)",
    category: "수산물",
    channel: "쿠거",
    currentPrice: 12300,
    yesterdayPrice: 12500,
    weekAgoPrice: 12100,
    twoWeeksAgoPrice: 12200,
    monthAgoPrice: 12000,
    yearAgoPrice: 11700,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 25,
    name: "오이 (1kg)",
    category: "채소/과일",
    channel: "쿠팡",
    currentPrice: 3500,
    yesterdayPrice: 3600,
    weekAgoPrice: 3400,
    twoWeeksAgoPrice: 3500,
    monthAgoPrice: 3300,
    yearAgoPrice: 3000,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 79,
    name: "오이 (1kg)",
    category: "채소/과일",
    channel: "마켓대리",
    currentPrice: 3600,
    yesterdayPrice: 3700,
    weekAgoPrice: 3500,
    twoWeeksAgoPrice: 3600,
    monthAgoPrice: 3400,
    yearAgoPrice: 3100,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 80,
    name: "오이 (1kg)",
    category: "채소/과일",
    channel: "쿠거",
    currentPrice: 3700,
    yesterdayPrice: 3800,
    weekAgoPrice: 3600,
    twoWeeksAgoPrice: 3700,
    monthAgoPrice: 3500,
    yearAgoPrice: 3200,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 26,
    name: "토마토 (1kg)",
    category: "채소/과일",
    channel: "쿠팡",
    currentPrice: 4500,
    yesterdayPrice: 4600,
    weekAgoPrice: 4400,
    twoWeeksAgoPrice: 4500,
    monthAgoPrice: 4300,
    yearAgoPrice: 4000,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 81,
    name: "토마토 (1kg)",
    category: "채소/과일",
    channel: "마켓대리",
    currentPrice: 4600,
    yesterdayPrice: 4700,
    weekAgoPrice: 4500,
    twoWeeksAgoPrice: 4600,
    monthAgoPrice: 4400,
    yearAgoPrice: 4100,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 82,
    name: "토마토 (1kg)",
    category: "채소/과일",
    channel: "쿠거",
    currentPrice: 4700,
    yesterdayPrice: 4800,
    weekAgoPrice: 4600,
    twoWeeksAgoPrice: 4700,
    monthAgoPrice: 4500,
    yearAgoPrice: 4200,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 27,
    name: "간장 (1.8L)",
    category: "가공",
    channel: "쿠팡",
    currentPrice: 6500,
    yesterdayPrice: 6600,
    weekAgoPrice: 6400,
    twoWeeksAgoPrice: 6500,
    monthAgoPrice: 6300,
    yearAgoPrice: 6000,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 83,
    name: "간장 (1.8L)",
    category: "가공",
    channel: "마켓대리",
    currentPrice: 6600,
    yesterdayPrice: 6700,
    weekAgoPrice: 6500,
    twoWeeksAgoPrice: 6600,
    monthAgoPrice: 6400,
    yearAgoPrice: 6100,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 84,
    name: "간장 (1.8L)",
    category: "가공",
    channel: "쿠거",
    currentPrice: 6700,
    yesterdayPrice: 6800,
    weekAgoPrice: 6600,
    twoWeeksAgoPrice: 6700,
    monthAgoPrice: 6500,
    yearAgoPrice: 6200,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 28,
    name: "참기름 (500ml)",
    category: "가공",
    channel: "쿠팡",
    currentPrice: 12000,
    yesterdayPrice: 12200,
    weekAgoPrice: 11800,
    twoWeeksAgoPrice: 11900,
    monthAgoPrice: 11700,
    yearAgoPrice: 11400,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 85,
    name: "참기름 (500ml)",
    category: "가공",
    channel: "마켓대리",
    currentPrice: 12200,
    yesterdayPrice: 12400,
    weekAgoPrice: 12000,
    twoWeeksAgoPrice: 12100,
    monthAgoPrice: 11900,
    yearAgoPrice: 11600,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 86,
    name: "참기름 (500ml)",
    category: "가공",
    channel: "쿠거",
    currentPrice: 12300,
    yesterdayPrice: 12500,
    weekAgoPrice: 12100,
    twoWeeksAgoPrice: 12200,
    monthAgoPrice: 12000,
    yearAgoPrice: 11700,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 29,
    name: "식용유 (1.8L)",
    category: "가공",
    channel: "쿠팡",
    currentPrice: 8500,
    yesterdayPrice: 8600,
    weekAgoPrice: 8400,
    twoWeeksAgoPrice: 8500,
    monthAgoPrice: 8300,
    yearAgoPrice: 8000,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 87,
    name: "식용유 (1.8L)",
    category: "가공",
    channel: "마켓대리",
    currentPrice: 8600,
    yesterdayPrice: 8700,
    weekAgoPrice: 8500,
    twoWeeksAgoPrice: 8600,
    monthAgoPrice: 8400,
    yearAgoPrice: 8100,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 88,
    name: "식용유 (1.8L)",
    category: "가공",
    channel: "쿠거",
    currentPrice: 8700,
    yesterdayPrice: 8800,
    weekAgoPrice: 8600,
    twoWeeksAgoPrice: 8700,
    monthAgoPrice: 8500,
    yearAgoPrice: 8200,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 30,
    name: "설탕 (3kg)",
    category: "가공",
    channel: "마켓대리",
    currentPrice: 5500,
    yesterdayPrice: 5600,
    weekAgoPrice: 5400,
    twoWeeksAgoPrice: 5500,
    monthAgoPrice: 5300,
    yearAgoPrice: 5000,
    trend: "down",
    isLowestPrice: false,
  },
  {
    id: 89,
    name: "설탕 (3kg)",
    category: "가공",
    channel: "쿠거",
    currentPrice: 5600,
    yesterdayPrice: 5700,
    weekAgoPrice: 5500,
    twoWeeksAgoPrice: 5600,
    monthAgoPrice: 5400,
    yearAgoPrice: 5100,
    trend: "down",
    isLowestPrice: false,
  },
];

export const InventoryOverview = () => {
  const [selectedCategory, setSelectedCategory] = useState<string>("전체");
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 10;

  const filteredData = selectedCategory === "전체" 
    ? mockInventoryData 
    : mockInventoryData.filter(item => item.category === selectedCategory);

  const totalPages = Math.ceil(filteredData.length / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const paginatedData = filteredData.slice(startIndex, startIndex + itemsPerPage);

  const handlePageChange = (page: number) => {
    setCurrentPage(page);
  };

  return (
    <div className="space-y-6">
      <TopIngredientsPriceChart data={mockInventoryData} />
      
      <Card className="p-6">
        <div className="flex justify-between items-center mb-6">
          <h3 className="text-lg font-semibold">식자재 가격 현황</h3>
          <Select value={selectedCategory} onValueChange={setSelectedCategory}>
            <SelectTrigger className="w-[180px]">
              <SelectValue placeholder="카테고리 선택" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="전체">전체</SelectItem>
              <SelectItem value="축산물">축산물</SelectItem>
              <SelectItem value="수산물">수산물</SelectItem>
              <SelectItem value="채소/과일">채소/과일</SelectItem>
              <SelectItem value="가공">가공</SelectItem>
            </SelectContent>
          </Select>
        </div>
        
        <div className="overflow-x-auto">
          <InventoryTable data={paginatedData} />
        </div>

        <div className="mt-4">
          <Pagination>
            <PaginationContent>
              <PaginationItem>
                <PaginationPrevious 
                  onClick={() => handlePageChange(Math.max(1, currentPage - 1))}
                  className={currentPage === 1 ? "pointer-events-none opacity-50" : "cursor-pointer"}
                />
              </PaginationItem>
              {Array.from({ length: totalPages }, (_, i) => i + 1).map((page) => (
                <PaginationItem key={page}>
                  <PaginationLink
                    onClick={() => handlePageChange(page)}
                    isActive={currentPage === page}
                    className="cursor-pointer"
                  >
                    {page}
                  </PaginationLink>
                </PaginationItem>
              ))}
              <PaginationItem>
                <PaginationNext 
                  onClick={() => handlePageChange(Math.min(totalPages, currentPage + 1))}
                  className={currentPage === totalPages ? "pointer-events-none opacity-50" : "cursor-pointer"}
                />
              </PaginationItem>
            </PaginationContent>
          </Pagination>
        </div>
      </Card>
    </div>
  );
};
